a=int(input("enter frist number:"))
b=int(input("enter second number:"))
print("******comparison operators******")
print("is equals:",a==b)
print("is not equals:",a!=b)
print("greater than:",a>b)
print("less than:",a<b)
print("less than equals:",a<=b)
print("greater than equals:",a>=b)
